"""empty message

Revision ID: 0704498ff846
Revises: 6393aba230f7
Create Date: 2023-03-19 15:18:00.102661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0704498ff846'
down_revision = '6393aba230f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=255), nullable=True))
        batch_op.drop_column('reply')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('message')

    # ### end Alembic commands ###
